### ISSUE TITLE
Exception on callback

### ISSUE THREAD

**Issue by howdoicomputer** [shinyscorpion/ueberauth_steam#4]
```
[info] GET /auth/steam/callback
[debug] Processing with DropsquadsWeb.AuthController.callback/2
  Parameters: %{"openid.assoc_handle" => "1234567890", "openid.claimed_id" => "https://steamcommunity.com/openid/id/76561198020220006", "openid.identity" => "https://steamcommunity.com/openid/id/76561198020220006", "openid.mode" => "id_res", "openid.ns" => "http://specs.openid.net/auth/2.0", "openid.op_endpoint" => "https://steamcommunity.com/openid/login", "openid.response_nonce" => "2018-05-05T17:43:32ZcIyuKWjMHYPSjms0UBt4txzkyhc=", "openid.return_to" => "http://127.0.0.1:4000/auth/steam/callback", "openid.sig" => "VyYdNx0Ab2kdzpvb5AXBV07+yj8=", "openid.signed" => "signed,op_endpoint,claimed_id,identity,return_to,response_nonce,assoc_handle", "provider" => "steam"}
  Pipelines: [:browser]
[error] Task #PID<0.415.0> started from #PID<0.408.0> terminating
** (FunctionClauseError) no function clause matching in Ueberauth.Strategy.Steam.retrieve_user/1
    (ueberauth_steam) lib/ueberauth/strategy/steam.ex:112: Ueberauth.Strategy.Steam.retrieve_user(%{"openid.assoc_handle" => "1234567890", "openid.claimed_id" => "https://steamcommunity.com/openid/id/76561198020220006", "openid.identity" => "https://steamcommunity.com/openid/id/76561198020220006", "openid.mode" => "id_res", "openid.ns" => "http://specs.openid.net/auth/2.0", "openid.op_endpoint" => "https://steamcommunity.com/openid/login", "openid.response_nonce" => "2018-05-05T17:43:32ZcIyuKWjMHYPSjms0UBt4txzkyhc=", "openid.return_to" => "http://127.0.0.1:4000/auth/steam/callback", "openid.sig" => "VyYdNx0Ab2kdzpvb5AXBV07+yj8=", "openid.signed" => "signed,op_endpoint,claimed_id,identity,return_to,response_nonce,assoc_handle", "provider" => "steam"})
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<1.113179099/0 in Ueberauth.Strategy.Steam.handle_callback!/1>
    Args: []
[error] Ranch protocol #PID<0.408.0> (:cowboy_protocol) of listener DropsquadsWeb.Endpoint.HTTP terminated
```

**Comment by howdoicomputer** [comment]
https://github.com/kouwasi/ueberauth_steam fixes the matching error
